name: Node.js CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-ci:
    uses: rg-hermann/workflow-templates/.github/workflows/ci-node.yaml@feature/node-ci
    with:
      node-version: '22'
      install-command: 'npm ci'
      build-command: 'npm run build'
      test-command: 'npm test'
      run-npm-audit: true
      run-codeql: true
      run-dependency-review: true
